/**
 * Hand-authored symbol table for `fixtures/sample-analysis.json`.
 *
 * Split out of `fixture-data.ts` to keep both files under the 800-line
 * ceiling (acceptance criterion 27). Covers every `SymbolKind` member so the
 * UI has a real example of each to render.
 *
 * Authoring order is irrelevant: `build-fixture.ts` sorts by (path, startLine)
 * before emitting, and the fixture sort-order test re-verifies the result.
 */

export const SYMBOLS = [
  {
    id: 'a1b2c3d4e5f60001',
    name: 'AuthController',
    kind: 'class' as const,
    path: 'src/controllers/auth.controller.ts',
    startLine: 12,
    endLine: 88,
    isExported: true,
    containerName: null,
    signature: 'class AuthController',
  },
  {
    id: 'a1b2c3d4e5f60002',
    name: 'login',
    kind: 'method' as const,
    path: 'src/controllers/auth.controller.ts',
    startLine: 19,
    endLine: 44,
    isExported: false,
    containerName: 'AuthController',
    signature: 'async login(req: Request, res: Response): Promise<void>',
  },
  {
    id: 'a1b2c3d4e5f60003',
    name: 'logout',
    kind: 'method' as const,
    path: 'src/controllers/auth.controller.ts',
    startLine: 46,
    endLine: 61,
    isExported: false,
    containerName: 'AuthController',
    signature: 'async logout(req: Request, res: Response): Promise<void>',
  },
  {
    id: 'a1b2c3d4e5f60004',
    name: 'BillingController',
    kind: 'class' as const,
    path: 'src/controllers/billing.controller.ts',
    startLine: 10,
    endLine: 79,
    isExported: true,
    containerName: null,
    signature: 'class BillingController',
  },
  {
    id: 'a1b2c3d4e5f60005',
    name: 'createInvoice',
    kind: 'method' as const,
    path: 'src/controllers/billing.controller.ts',
    startLine: 17,
    endLine: 48,
    isExported: false,
    containerName: 'BillingController',
    signature: 'async createInvoice(req: Request, res: Response): Promise<void>',
  },
  {
    id: 'a1b2c3d4e5f60006',
    name: 'EnvSchema',
    kind: 'const' as const,
    path: 'src/config/env.ts',
    startLine: 5,
    endLine: 21,
    isExported: true,
    containerName: null,
    signature: 'const EnvSchema: z.ZodObject',
  },
  {
    id: 'a1b2c3d4e5f60007',
    name: 'Env',
    kind: 'type' as const,
    path: 'src/config/env.ts',
    startLine: 23,
    endLine: 23,
    isExported: true,
    containerName: null,
    signature: 'type Env = z.infer<typeof EnvSchema>',
  },
  {
    id: 'a1b2c3d4e5f60008',
    name: 'loadEnv',
    kind: 'function' as const,
    path: 'src/config/env.ts',
    startLine: 25,
    endLine: 44,
    isExported: true,
    containerName: null,
    signature: 'function loadEnv(): Env',
  },
  {
    id: 'a1b2c3d4e5f60009',
    name: 'pool',
    kind: 'const' as const,
    path: 'src/db/client.ts',
    startLine: 8,
    endLine: 14,
    isExported: true,
    containerName: null,
    signature: 'const pool: Pool',
  },
  {
    id: 'a1b2c3d4e5f60010',
    name: 'query',
    kind: 'function' as const,
    path: 'src/db/client.ts',
    startLine: 16,
    endLine: 38,
    isExported: true,
    containerName: null,
    signature: 'async function query<T>(sql: string, params: unknown[]): Promise<T[]>',
  },
  {
    id: 'a1b2c3d4e5f60011',
    name: 'main',
    kind: 'function' as const,
    path: 'src/index.ts',
    startLine: 5,
    endLine: 20,
    isExported: false,
    containerName: null,
    signature: 'async function main(): Promise<void>',
  },
  {
    id: 'a1b2c3d4e5f60012',
    name: 'sendMail',
    kind: 'function' as const,
    path: 'src/legacy/old-mailer.ts',
    startLine: 9,
    endLine: 48,
    isExported: true,
    containerName: null,
    signature: 'function sendMail(to: string, body: string): void',
  },
  {
    id: 'a1b2c3d4e5f60013',
    name: 'UserRole',
    kind: 'enum' as const,
    path: 'src/models/user.model.ts',
    startLine: 6,
    endLine: 11,
    isExported: true,
    containerName: null,
    signature: 'enum UserRole',
  },
  {
    id: 'a1b2c3d4e5f60014',
    name: 'User',
    kind: 'interface' as const,
    path: 'src/models/user.model.ts',
    startLine: 13,
    endLine: 22,
    isExported: true,
    containerName: null,
    signature: 'interface User',
  },
  {
    id: 'a1b2c3d4e5f60015',
    name: 'findUserByEmail',
    kind: 'function' as const,
    path: 'src/models/user.model.ts',
    startLine: 24,
    endLine: 51,
    isExported: true,
    containerName: null,
    signature: 'async function findUserByEmail(email: string): Promise<User | null>',
  },
  {
    id: 'a1b2c3d4e5f60016',
    name: 'authRouter',
    kind: 'route' as const,
    path: 'src/routes/auth.routes.ts',
    startLine: 6,
    endLine: 33,
    isExported: true,
    containerName: null,
    signature: 'const authRouter: Router',
  },
  {
    id: 'a1b2c3d4e5f60017',
    name: 'billingRouter',
    kind: 'route' as const,
    path: 'src/routes/billing.routes.ts',
    startLine: 6,
    endLine: 30,
    isExported: true,
    containerName: null,
    signature: 'const billingRouter: Router',
  },
  {
    id: 'a1b2c3d4e5f60018',
    name: 'createServer',
    kind: 'function' as const,
    path: 'src/server.ts',
    startLine: 10,
    endLine: 55,
    isExported: true,
    containerName: null,
    signature: 'function createServer(): Express',
  },
  {
    id: 'a1b2c3d4e5f60019',
    name: 'AuthService',
    kind: 'class' as const,
    path: 'src/services/auth.service.ts',
    startLine: 14,
    endLine: 132,
    isExported: true,
    containerName: null,
    signature: 'class AuthService',
  },
  {
    id: 'a1b2c3d4e5f60020',
    name: 'authenticate',
    kind: 'method' as const,
    path: 'src/services/auth.service.ts',
    startLine: 22,
    endLine: 68,
    isExported: false,
    containerName: 'AuthService',
    signature: 'async authenticate(email: string, password: string): Promise<Session>',
  },
  {
    id: 'a1b2c3d4e5f60021',
    name: 'MAX_LOGIN_ATTEMPTS',
    kind: 'const' as const,
    path: 'src/services/auth.service.ts',
    startLine: 12,
    endLine: 12,
    isExported: false,
    containerName: null,
    signature: 'const MAX_LOGIN_ATTEMPTS = 5',
  },
  {
    id: 'a1b2c3d4e5f60022',
    name: 'BillingService',
    kind: 'class' as const,
    path: 'src/services/billing.service.ts',
    startLine: 11,
    endLine: 104,
    isExported: true,
    containerName: null,
    signature: 'class BillingService',
  },
  {
    id: 'a1b2c3d4e5f60023',
    name: 'SessionService',
    kind: 'class' as const,
    path: 'src/services/session.service.ts',
    startLine: 9,
    endLine: 80,
    isExported: true,
    containerName: null,
    signature: 'class SessionService',
  },
  {
    id: 'a1b2c3d4e5f60024',
    name: 'Session',
    kind: 'interface' as const,
    path: 'src/services/session.service.ts',
    startLine: 4,
    endLine: 7,
    isExported: true,
    containerName: null,
    signature: 'interface Session',
  },
  {
    id: 'a1b2c3d4e5f60025',
    name: 'signToken',
    kind: 'function' as const,
    path: 'src/services/token.service.ts',
    startLine: 11,
    endLine: 39,
    isExported: true,
    containerName: null,
    signature: 'function signToken(payload: TokenPayload): string',
  },
  {
    id: 'a1b2c3d4e5f60026',
    name: 'verifyToken',
    kind: 'function' as const,
    path: 'src/services/token.service.ts',
    startLine: 41,
    endLine: 74,
    isExported: true,
    containerName: null,
    signature: 'function verifyToken(token: string): TokenPayload | null',
  },
  {
    id: 'a1b2c3d4e5f60027',
    name: 'formatCurrency',
    kind: 'function' as const,
    path: 'src/utils/format.ts',
    startLine: 4,
    endLine: 18,
    isExported: true,
    containerName: null,
    signature: 'function formatCurrency(cents: number, currency: string): string',
  },
  {
    id: 'a1b2c3d4e5f60028',
    name: 'logger',
    kind: 'variable' as const,
    path: 'src/utils/logger.ts',
    startLine: 8,
    endLine: 12,
    isExported: true,
    containerName: null,
    signature: 'const logger: Logger',
  },
  {
    id: 'a1b2c3d4e5f60029',
    name: 'App',
    kind: 'component' as const,
    path: 'web/src/App.tsx',
    startLine: 6,
    endLine: 52,
    isExported: true,
    containerName: null,
    signature: 'function App(): JSX.Element',
  },
  {
    id: 'a1b2c3d4e5f60030',
    name: 'LoginForm',
    kind: 'component' as const,
    path: 'web/src/components/LoginForm.tsx',
    startLine: 14,
    endLine: 97,
    isExported: true,
    containerName: null,
    signature: 'function LoginForm({ onSuccess }: LoginFormProps): JSX.Element',
  },
  {
    id: 'a1b2c3d4e5f60031',
    name: 'useSession',
    kind: 'hook' as const,
    path: 'web/src/components/LoginForm.tsx',
    startLine: 6,
    endLine: 12,
    isExported: false,
    containerName: null,
    signature: 'function useSession(): SessionState',
  },
  {
    id: 'a1b2c3d4e5f60032',
    name: 'run',
    kind: 'function' as const,
    path: 'worker/main.py',
    startLine: 18,
    endLine: 52,
    isExported: true,
    containerName: null,
    signature: 'def run(batch_size: int = 100) -> None',
  },
];
