import { describe, expect, test } from 'bun:test';
import { classifyFile, type ClassifyFileInput } from '../../src/classify/classify-file';
import { CLASSIFICATION_RULE_ORDER } from '../../src/classify/convention-tables';

function classify(path: string, overrides: Partial<ClassifyFileInput> = {}): string {
  return classifyFile({ path, isEntryPoint: false, headerLines: [], ...overrides });
}

describe('classifyFile — rule 1: entrypoint', () => {
  test('classifies a file the caller flagged as an entry point above every other rule', () => {
    expect(classify('src/utils/index.ts', { isEntryPoint: true })).toBe('entrypoint');
  });
});

describe('classifyFile — rule 2: test', () => {
  test('classifies a __tests__ directory segment as test', () => {
    expect(classify('src/__tests__/thing.ts')).toBe('test');
  });

  test('classifies a *.test.ts basename as test', () => {
    expect(classify('src/api/user.test.ts')).toBe('test');
  });

  test('classifies a *.spec.tsx basename as test', () => {
    expect(classify('src/components/Button.spec.tsx')).toBe('test');
  });

  test('classifies a Python test_*.py basename as test', () => {
    expect(classify('app/test_user.py')).toBe('test');
  });

  test('classifies a Python *_test.py basename as test', () => {
    expect(classify('app/user_test.py')).toBe('test');
  });

  test('test wins over util even though "utils" is also a segment', () => {
    expect(classify('src/utils/__tests__/helpers.ts')).toBe('test');
  });
});

describe('classifyFile — rule 3: fixture', () => {
  test('classifies a fixtures directory segment as fixture', () => {
    expect(classify('src/fixtures/sample.json')).toBe('fixture');
  });

  test('test (rule 2) outranks fixture (rule 3) when both segments are present', () => {
    expect(classify('test/fixtures/sample.json')).toBe('test');
  });

  test('classifies a __mocks__ directory segment as fixture', () => {
    expect(classify('src/__mocks__/api.ts')).toBe('fixture');
  });
});

describe('classifyFile — rule 4: style', () => {
  test('classifies a .scss file as style', () => {
    expect(classify('src/components/Button.scss')).toBe('style');
  });
});

describe('classifyFile — rule 5: docs', () => {
  test('classifies a .md file as docs', () => {
    expect(classify('README.md')).toBe('docs');
  });

  test('classifies anything under a docs/ segment as docs', () => {
    expect(classify('docs/ARCHITECTURE.rst')).toBe('docs');
  });
});

describe('classifyFile — rule 6: config', () => {
  test('classifies package.json (a known config filename) as config', () => {
    expect(classify('package.json')).toBe('config');
  });

  test('classifies a .yaml file by extension as config', () => {
    expect(classify('src/config/deploy.yaml')).toBe('config');
  });

  test('classifies anything under a config/ segment as config', () => {
    expect(classify('config/database.ts')).toBe('config');
  });

  test('classifies Dockerfile (extensionless conventional name) as config', () => {
    expect(classify('Dockerfile')).toBe('config');
  });
});

describe('classifyFile — rule 7: generated', () => {
  test('classifies a file with an @generated header marker as generated', () => {
    expect(classify('src/api/client.ts', { headerLines: ['// @generated by protoc'] })).toBe('generated');
  });

  test('classifies a file with a DO NOT EDIT header marker as generated', () => {
    expect(classify('src/api/client.ts', { headerLines: ['// Code generated. DO NOT EDIT.'] })).toBe('generated');
  });

  test('ignores a header marker outside the first 3 lines', () => {
    const headerLines = ['line 1', 'line 2', 'line 3', '// @generated'];
    expect(classify('src/other/client.ts', { headerLines })).toBe('unknown');
  });

  test('classifies a *.pb.go-style basename infix as generated', () => {
    expect(classify('src/api/user.pb.ts')).toBe('generated');
  });
});

describe('classifyFile — rules 8-16: directory-segment conventions, in priority order', () => {
  test.each([
    ['src/routes/user.ts', 'route'],
    ['src/controllers/user.ts', 'controller'],
    ['src/services/billing.ts', 'service'],
    ['src/models/user.ts', 'model'],
    ['src/components/Card.ts', 'component'],
    ['src/hooks/useThing.ts', 'hook'],
    ['src/store/cartSlice.ts', 'store'],
    ['src/utils/format.ts', 'util'],
    ['scripts/migrate.ts', 'script'],
  ] as const)('classifies %s as %s', (path, expected) => {
    expect(classify(path)).toBe(expected);
  });

  test('a PascalCase .tsx basename is a component even outside a components/ segment', () => {
    expect(classify('src/features/billing/InvoiceCard.tsx')).toBe('component');
  });

  test('a use[A-Z] basename is a hook even outside a hooks/ segment', () => {
    expect(classify('src/features/billing/useInvoice.ts')).toBe('hook');
  });

  test('route (rule 8) outranks service (rule 10) when both segments are present', () => {
    expect(classify('src/services/routes/health.ts')).toBe('route');
  });
});

describe('classifyFile — rule 17: asset', () => {
  test('classifies an .html file as asset', () => {
    expect(classify('public/index.html')).toBe('asset');
  });
});

describe('classifyFile — rule 18: unknown', () => {
  test('classifies a file matching no rule as unknown', () => {
    expect(classify('src/weird/thing.xyz')).toBe('unknown');
  });
});

describe('classifyFile — segment matching is case-insensitive', () => {
  test('matches a segment regardless of case', () => {
    expect(classify('src/Controllers/User.ts')).toBe('controller');
  });
});

describe('CLASSIFICATION_RULE_ORDER', () => {
  test('documents all 18 classifications with entrypoint first and unknown last', () => {
    expect(CLASSIFICATION_RULE_ORDER).toHaveLength(18);
    expect(CLASSIFICATION_RULE_ORDER[0]).toBe('entrypoint');
    expect(CLASSIFICATION_RULE_ORDER.at(-1)).toBe('unknown');
  });
});
