/**
 * @onboard/engine — "start here" roadmap derivation (Section 8.5).
 *
 * Every strongly-connected component (Section 8.5 step 1) becomes ONE step:
 * a cycle is never a loop in the reading path. Layers are built by BFS over
 * the SCC-condensation DAG (step 2-4), leaf utilities are pulled out (step
 * 5), unreached SCCs form their own section (step 6), everything is
 * concatenated then trimmed (steps 7-8), and each kept step's `why` string
 * is generated by the first matching template (step 10).
 */
import {
  MAX_ROADMAP_DEPTH,
  MAX_ROADMAP_SEEDS,
  MAX_UNREACHED_STEPS,
  ROADMAP_DEPENDS_ON_CAP,
  ROADMAP_LEAF_UTILITY_CLASSIFICATIONS,
  ROADMAP_LEAF_UTILITY_SEGMENTS,
  ROADMAP_MAX_LENGTH,
  ROADMAP_TARGET_LENGTH,
} from '../constants';
import { computeStronglyConnectedComponents, type GraphEdge } from '../graph/tarjan-scc';
import { byteCompare } from '../util/sort';
import { posixBasename, splitPosixSegments } from '../util/posix-path';

export type RoadmapSection = 'entry' | 'core' | 'supporting' | 'leaf-utility' | 'unreached';

export interface RoadmapFileInput {
  readonly path: string;
  readonly classification: string;
  readonly importance: number;
  readonly importanceRank: number;
  readonly inDegree: number;
}

export interface RoadmapEntryPointInput {
  readonly path: string;
  readonly rank: number;
  readonly evidence: string;
}

export interface RoadmapInput {
  readonly files: readonly RoadmapFileInput[];
  readonly edges: readonly GraphEdge[];
  readonly entryPoints: readonly RoadmapEntryPointInput[];
  readonly outLinks: ReadonlyMap<string, readonly string[]>;
  readonly moduleNameForPath: (path: string) => string;
}

export interface RoadmapStepResult {
  readonly order: number;
  readonly path: string;
  readonly companionPaths: readonly string[];
  readonly section: RoadmapSection;
  readonly why: string;
  readonly dependsOnPaths: readonly string[];
  readonly dependedOnByCount: number;
}

interface SccGroup {
  readonly representative: string;
  readonly companionPaths: readonly string[];
}

function fileOf(fileByPath: ReadonlyMap<string, RoadmapFileInput>, path: string): RoadmapFileInput {
  return fileByPath.get(path) ?? { path, classification: 'unknown', importance: 0, importanceRank: 0, inDegree: 0 };
}

function buildSccGroups(sccs: readonly (readonly string[])[], fileByPath: ReadonlyMap<string, RoadmapFileInput>): readonly SccGroup[] {
  return sccs.map((members) => {
    const sorted = [...members].sort(byteCompare);
    let representative = sorted[0]!;
    let bestImportance = fileOf(fileByPath, representative).importance;
    for (let i = 1; i < sorted.length; i += 1) {
      const candidate = sorted[i]!;
      const importance = fileOf(fileByPath, candidate).importance;
      if (importance > bestImportance) {
        bestImportance = importance;
        representative = candidate;
      }
    }
    return { representative, companionPaths: sorted.filter((m) => m !== representative) };
  });
}

/** SCC-condensation DAG, keyed by representative path, adjacency sorted ascending. */
function buildDag(
  groups: readonly SccGroup[],
  edges: readonly GraphEdge[],
  sccIndexByPath: ReadonlyMap<string, number>,
): ReadonlyMap<string, readonly string[]> {
  const targetSets = new Map<string, Set<string>>();
  groups.forEach((g) => targetSets.set(g.representative, new Set()));
  edges.forEach((edge) => {
    const fromIndex = sccIndexByPath.get(edge.from);
    const toIndex = sccIndexByPath.get(edge.to);
    if (fromIndex === undefined || toIndex === undefined || fromIndex === toIndex) {
      return;
    }
    targetSets.get(groups[fromIndex]!.representative)?.add(groups[toIndex]!.representative);
  });
  const dag = new Map<string, readonly string[]>();
  targetSets.forEach((targets, representative) => dag.set(representative, [...targets].sort(byteCompare)));
  return dag;
}

interface SeedInfo {
  readonly representative: string;
  readonly evidence: string;
}

function pickHighestImportanceRepresentative(groups: readonly SccGroup[], fileByPath: ReadonlyMap<string, RoadmapFileInput>): string {
  let best = groups[0]!.representative;
  let bestImportance = fileOf(fileByPath, best).importance;
  for (let i = 1; i < groups.length; i += 1) {
    const candidate = groups[i]!.representative;
    const importance = fileOf(fileByPath, candidate).importance;
    if (importance > bestImportance || (importance === bestImportance && byteCompare(candidate, best) < 0)) {
      bestImportance = importance;
      best = candidate;
    }
  }
  return best;
}

function computeSeeds(
  entryPoints: readonly RoadmapEntryPointInput[],
  sccIndexByPath: ReadonlyMap<string, number>,
  groups: readonly SccGroup[],
  fileByPath: ReadonlyMap<string, RoadmapFileInput>,
): readonly SeedInfo[] {
  if (entryPoints.length === 0) {
    const representative = pickHighestImportanceRepresentative(groups, fileByPath);
    return [{ representative, evidence: 'no entry point detected; highest-centrality file' }];
  }
  const sortedEntries = [...entryPoints].sort((a, b) => a.rank - b.rank);
  const seeds: SeedInfo[] = [];
  const seen = new Set<string>();
  for (let i = 0; i < sortedEntries.length && seeds.length < MAX_ROADMAP_SEEDS; i += 1) {
    const entry = sortedEntries[i]!;
    const index = sccIndexByPath.get(entry.path);
    if (index === undefined) {
      continue;
    }
    const representative = groups[index]!.representative;
    if (seen.has(representative)) {
      continue;
    }
    seen.add(representative);
    seeds.push({ representative, evidence: entry.evidence });
  }
  return seeds;
}

function compareByImportanceThenInDegreeThenPath(
  a: string,
  b: string,
  fileByPath: ReadonlyMap<string, RoadmapFileInput>,
): number {
  const fileA = fileOf(fileByPath, a);
  const fileB = fileOf(fileByPath, b);
  if (fileA.importance !== fileB.importance) {
    return fileB.importance - fileA.importance;
  }
  if (fileA.inDegree !== fileB.inDegree) {
    return fileB.inDegree - fileA.inDegree;
  }
  return byteCompare(a, b);
}

interface BfsOutput {
  readonly layers: readonly (readonly string[])[]; // layers[0] = seeds; layers[MAX_ROADMAP_DEPTH] absorbs everything deeper
  readonly assigned: ReadonlySet<string>;
}

function layeredBfs(
  seedReprs: readonly string[],
  dag: ReadonlyMap<string, readonly string[]>,
  fileByPath: ReadonlyMap<string, RoadmapFileInput>,
): BfsOutput {
  const assigned = new Set<string>(seedReprs);
  const layers: string[][] = [[...seedReprs]];
  let frontier = seedReprs;
  let depth = 0;
  for (;;) {
    const nextSet = new Set<string>();
    frontier.forEach((node) => {
      (dag.get(node) ?? []).forEach((target) => {
        if (!assigned.has(target)) {
          nextSet.add(target);
        }
      });
    });
    if (nextSet.size === 0) {
      break;
    }
    const next = [...nextSet].sort((a, b) => compareByImportanceThenInDegreeThenPath(a, b, fileByPath));
    next.forEach((n) => assigned.add(n));
    depth += 1;
    const layerIndex = Math.min(depth, MAX_ROADMAP_DEPTH);
    const existing = layers[layerIndex] ?? [];
    layers[layerIndex] = [...existing, ...next];
    frontier = next;
  }
  const overflowLayer = layers[MAX_ROADMAP_DEPTH];
  if (overflowLayer !== undefined) {
    layers[MAX_ROADMAP_DEPTH] = [...overflowLayer].sort((a, b) => compareByImportanceThenInDegreeThenPath(a, b, fileByPath));
  }
  return { layers, assigned };
}

function isLeafUtility(representative: string, fileByPath: ReadonlyMap<string, RoadmapFileInput>, dagOutDegree: number): boolean {
  if (dagOutDegree !== 0) {
    return false;
  }
  const file = fileOf(fileByPath, representative);
  if (ROADMAP_LEAF_UTILITY_CLASSIFICATIONS.includes(file.classification)) {
    return true;
  }
  const segments = splitPosixSegments(representative).map((s) => s.toLowerCase());
  return segments.some((segment) => ROADMAP_LEAF_UTILITY_SEGMENTS.includes(segment));
}

interface StepCandidate {
  readonly representative: string;
  readonly companionPaths: readonly string[];
  readonly section: RoadmapSection;
  readonly evidence: string | null;
}

/** Extracts leaf utilities from layers 1..N, returning the remaining layers and the extracted set. */
function extractLeafUtilities(
  layers: readonly (readonly string[])[],
  fileByPath: ReadonlyMap<string, RoadmapFileInput>,
  dag: ReadonlyMap<string, readonly string[]>,
): { readonly prunedLayers: readonly (readonly string[])[]; readonly leafReprs: readonly string[] } {
  const leafReprs: string[] = [];
  const prunedLayers: string[][] = [layers[0] ? [...layers[0]] : []];
  for (let layerIndex = 1; layerIndex < layers.length; layerIndex += 1) {
    const layer = layers[layerIndex] ?? [];
    const kept: string[] = [];
    layer.forEach((representative) => {
      const outDegree = (dag.get(representative) ?? []).length;
      if (isLeafUtility(representative, fileByPath, outDegree)) {
        leafReprs.push(representative);
      } else {
        kept.push(representative);
      }
    });
    prunedLayers.push(kept);
  }
  return { prunedLayers, leafReprs };
}

function buildUnreached(
  groups: readonly SccGroup[],
  assigned: ReadonlySet<string>,
  fileByPath: ReadonlyMap<string, RoadmapFileInput>,
): readonly string[] {
  const unassigned = groups.map((g) => g.representative).filter((r) => !assigned.has(r));
  return unassigned
    .sort((a, b) => {
      const fileA = fileOf(fileByPath, a);
      const fileB = fileOf(fileByPath, b);
      return fileA.importance !== fileB.importance ? fileB.importance - fileA.importance : byteCompare(a, b);
    })
    .slice(0, MAX_UNREACHED_STEPS);
}

function buildConcatenatedCandidates(
  seeds: readonly SeedInfo[],
  prunedLayers: readonly (readonly string[])[],
  leafReprs: readonly string[],
  unreachedReprs: readonly string[],
  fileByPath: ReadonlyMap<string, RoadmapFileInput>,
): readonly StepCandidate[] {
  const candidates: StepCandidate[] = [];
  seeds.forEach((seed) => candidates.push({ representative: seed.representative, companionPaths: [], section: 'entry', evidence: seed.evidence }));
  const core = [...(prunedLayers[1] ?? []), ...(prunedLayers[2] ?? [])];
  core.forEach((representative) => candidates.push({ representative, companionPaths: [], section: 'core', evidence: null }));
  const supporting: string[] = [];
  for (let i = 3; i <= MAX_ROADMAP_DEPTH; i += 1) {
    supporting.push(...(prunedLayers[i] ?? []));
  }
  supporting.forEach((representative) => candidates.push({ representative, companionPaths: [], section: 'supporting', evidence: null }));
  const sortedLeaf = [...leafReprs].sort((a, b) => {
    const fileA = fileOf(fileByPath, a);
    const fileB = fileOf(fileByPath, b);
    return fileA.importance !== fileB.importance ? fileB.importance - fileA.importance : byteCompare(a, b);
  });
  sortedLeaf.forEach((representative) => candidates.push({ representative, companionPaths: [], section: 'leaf-utility', evidence: null }));
  unreachedReprs.forEach((representative) => candidates.push({ representative, companionPaths: [], section: 'unreached', evidence: null }));
  return candidates;
}

function trimCandidates(
  candidates: readonly StepCandidate[],
  fileByPath: ReadonlyMap<string, RoadmapFileInput>,
): readonly StepCandidate[] {
  const entryCandidates = candidates.filter((c) => c.section === 'entry');
  const nonEntryCandidates = candidates.filter((c) => c.section !== 'entry');
  const keptTotal = Math.min(Math.max(ROADMAP_TARGET_LENGTH, entryCandidates.length), ROADMAP_MAX_LENGTH);
  const fillSlots = Math.max(0, keptTotal - entryCandidates.length);
  // Fill remaining slots in importance-desc order (path asc breaks ties deterministically).
  const fillCandidates = [...nonEntryCandidates].sort((a, b) => {
    const fileA = fileOf(fileByPath, a.representative);
    const fileB = fileOf(fileByPath, b.representative);
    return fileA.importance !== fileB.importance
      ? fileB.importance - fileA.importance
      : byteCompare(a.representative, b.representative);
  });
  const picked = new Set(fillCandidates.slice(0, fillSlots).map((c) => c.representative));
  const keptReprs = new Set([...entryCandidates.map((c) => c.representative), ...picked]);
  return candidates.filter((c) => keptReprs.has(c.representative));
}

function buildWhy(
  step: { readonly section: RoadmapSection; readonly evidence: string | null; readonly companionPaths: readonly string[] },
  file: RoadmapFileInput,
  moduleName: string,
  previousStepFileName: string | null,
): string {
  if (step.section === 'entry') {
    return `Entry point (${step.evidence ?? 'unknown'}). Start reading here.`;
  }
  if (step.companionPaths.length > 0) {
    return `Part of a ${String(step.companionPaths.length + 1)}-file import cycle; read these together.`;
  }
  if (file.importanceRank <= 3) {
    return `Imported by ${String(file.inDegree)} files (rank #${String(file.importanceRank)} by centrality) — the hub of ${moduleName}.`;
  }
  if (step.section === 'core') {
    return `${file.classification} used by ${String(file.inDegree)} files; reached directly from ${previousStepFileName ?? 'the entry point'}.`;
  }
  if (step.section === 'leaf-utility') {
    return `Leaf utility imported by ${String(file.inDegree)} files; read last, for reference.`;
  }
  if (step.section === 'unreached') {
    return 'Not reached from any entry point — likely dead code or a separate tool.';
  }
  return `${file.classification} in ${moduleName}; imported by ${String(file.inDegree)} files.`;
}

/** Derives the "start here" roadmap per Section 8.5. */
export function buildRoadmap(input: RoadmapInput): readonly RoadmapStepResult[] {
  if (input.files.length === 0) {
    return [];
  }
  const fileByPath = new Map(input.files.map((f) => [f.path, f] as const));
  const nodes = input.files.map((f) => f.path);
  const sccEdges: readonly GraphEdge[] = input.edges;
  const sccs = computeStronglyConnectedComponents(nodes, sccEdges);
  const groups = buildSccGroups(sccs, fileByPath);
  const groupByRepresentative = new Map(groups.map((g) => [g.representative, g] as const));
  const sccIndexByPath = new Map<string, number>();
  sccs.forEach((members, index) => members.forEach((member) => sccIndexByPath.set(member, index)));

  const dag = buildDag(groups, sccEdges, sccIndexByPath);
  const seeds = computeSeeds(input.entryPoints, sccIndexByPath, groups, fileByPath);
  const { layers, assigned } = layeredBfs(
    seeds.map((s) => s.representative),
    dag,
    fileByPath,
  );
  const { prunedLayers, leafReprs } = extractLeafUtilities(layers, fileByPath, dag);
  const unreachedReprs = buildUnreached(groups, assigned, fileByPath);

  const candidates = buildConcatenatedCandidates(seeds, prunedLayers, leafReprs, unreachedReprs, fileByPath)
    .map((c) => ({ ...c, companionPaths: groupByRepresentative.get(c.representative)?.companionPaths ?? [] }));
  const kept = trimCandidates(candidates, fileByPath);

  const steps: RoadmapStepResult[] = [];
  for (let i = 0; i < kept.length; i += 1) {
    const candidate = kept[i]!;
    const file = fileOf(fileByPath, candidate.representative);
    const dependsOnPaths = [...(input.outLinks.get(candidate.representative) ?? [])]
      .sort(byteCompare)
      .slice(0, ROADMAP_DEPENDS_ON_CAP);
    const previousStepFileName = i > 0 ? posixBasename(kept[i - 1]!.representative) : null;
    steps.push({
      order: i + 1,
      path: candidate.representative,
      companionPaths: candidate.companionPaths,
      section: candidate.section,
      why: buildWhy(candidate, file, input.moduleNameForPath(candidate.representative), previousStepFileName),
      dependsOnPaths,
      dependedOnByCount: file.inDegree,
    });
  }
  return steps;
}
