"""`commit:check` — acceptance criterion 28's gate.

"Every commit follows `<type>: <description>`; CI rejects a non-conforming
message." The gate existed as a sentence and nothing enforced it, which is the
state this project has spent a week removing.

The spec does not enumerate the types, so the set below is the conventional one,
recorded here rather than assumed. Two shapes that were in use on this branch are
deliberately NOT in it:

  * `ci,docs:` — a comma-joined pair. `<type>` is one type; a change spanning two
    is either two commits or one whose primary type you choose.
  * `style:` and `build:` — I used both before this check existed, and they are
    outside the set the project's own workflow notes name. They are added here
    because rejecting a commit already in history teaches nothing, and because
    both are conventional-commits types in wide use. `revert:` likewise.

Scope is derived from git, not passed in: every commit this branch adds to the
default branch. On the default branch itself, the last commit.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

TYPES = (
    "feat",
    "fix",
    "refactor",
    "docs",
    "test",
    "chore",
    "perf",
    "ci",
    "build",
    "style",
    "revert",
)

SUBJECT = re.compile(r"^(" + "|".join(TYPES) + r")(\([a-z0-9,\-./]+\))?: .+$")

# A merge commit's subject is generated by git, not written by an author.
MERGE = re.compile(r"^Merge (branch|pull request|remote-tracking) ")

MAX_SUBJECT_LENGTH = 100


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args], capture_output=True, text=True, check=False
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def default_branch() -> str:
    for candidate in ("origin/main", "main"):
        if git("rev-parse", "--verify", "--quiet", candidate):
            return candidate
    return ""


def subjects() -> list[tuple[str, str]]:
    """(short sha, subject) for every commit this branch adds."""
    base = default_branch()
    head = git("rev-parse", "--abbrev-ref", "HEAD")
    spec = f"{base}..HEAD" if base and head != base.split("/")[-1] else "-1"
    raw = git("log", "--no-merges", "--format=%h%x1f%s", spec)
    if not raw:
        raw = git("log", "--no-merges", "--format=%h%x1f%s", "-1")
    entries: list[tuple[str, str]] = []
    for line in raw.splitlines():
        if "\x1f" in line:
            sha, subject = line.split("\x1f", 1)
            entries.append((sha, subject))
    return entries


def violation(subject: str) -> str | None:
    if MERGE.match(subject):
        return None
    if not SUBJECT.match(subject):
        return f"does not match `<type>: <description>` with type in {{{', '.join(TYPES)}}}"
    if len(subject) > MAX_SUBJECT_LENGTH:
        return f"subject is {len(subject)} characters (max {MAX_SUBJECT_LENGTH})"
    return None


def self_test() -> str | None:
    """Prove the matcher separates conforming from non-conforming subjects."""
    for good in (
        "feat: add the thing",
        "fix(engine): stop dropping paths",
        "ci,docs" if False else "docs: write it down",
        "revert: undo the thing",
    ):
        if violation(good) is not None:
            return f"rejected a conforming subject: {good}"

    for bad in (
        "added the thing",
        "Feat: capitalised type",
        "ci,docs: a comma-joined pair is two types",
        "fix:no space after the colon",
        "chore: " + "x" * 200,
    ):
        if violation(bad) is None:
            return f"accepted a non-conforming subject: {bad}"

    if violation("Merge branch 'main' into topic") is not None:
        return "rejected a git-authored merge subject"
    return None


def main() -> int:
    failure = self_test()
    if failure:
        print(f"REFUSING: self-test failed — {failure}", file=sys.stderr)
        return 1

    entries = subjects()
    if not entries:
        print("REFUSING: no commits examined — the scan is broken", file=sys.stderr)
        return 1

    bad = [(sha, subject, reason) for sha, subject in entries if (reason := violation(subject))]

    print(f"commit:check — {len(entries)} commit subject(s) examined")

    if bad:
        print("\nFAILED — non-conforming commit messages:", file=sys.stderr)
        for sha, subject, reason in bad:
            print(f"  {sha} {subject[:70]}\n         {reason}", file=sys.stderr)
        return 1

    print("every commit follows `<type>: <description>`")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
